language : python
python:
    - "3.7"
    - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codeclimate-test-reporter

env:
 - FLASK_VERSION=1.0.2   

script: 
  - sudo pytest --cov=app
  - sudo coverage report -m

after_success:
  - coveralls
  - coverage xml
  - codeclimate-test-reporter

  